// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230104191745_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blog.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "My Business World"
                        },
                        new
                        {
                            Id = 3,
                            Name = "My Travels"
                        },
                        new
                        {
                            Id = 4,
                            Name = "My Kitchen"
                        });
                });

            modelBuilder.Entity("Blog.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3399),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3410),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3412),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3412),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3413),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3413),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3414),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3414),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3414),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3415),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3415),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3416),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3416),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3417),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3417),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3418),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3418),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3418),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3419),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3419),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3420),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3420),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3420),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3421),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3422),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3422),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3422),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3423),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3423),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3424),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3424),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3425),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3425),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3425),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3426),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3426),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3427),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3427),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3427),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3428),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3428),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3428),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3429),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3429),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3430),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3430),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3430),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3431),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3431),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3431),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3432),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3432),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3433),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3433),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3433),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3434),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3434),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3434),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3435),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3435),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3435),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3436),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3436),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3437),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3437),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3437),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3438),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3438),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3438),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3439),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3439),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3439),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3440),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3440),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3441),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3441),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3441),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3442),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3442),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3442),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3443),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3443),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3443),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3444),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3444),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3444),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3445),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3445),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3446),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3446),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3446),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3447),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3447),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3447),
                            Title = "Sample Text"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3448),
                            DateOfUpdate = new DateTime(2023, 1, 4, 22, 17, 45, 427, DateTimeKind.Local).AddTicks(3448),
                            Title = "Sample Text"
                        });
                });

            modelBuilder.Entity("CategoryPost", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "PostsId");

                    b.HasIndex("PostsId");

                    b.ToTable("CategoryPost");
                });

            modelBuilder.Entity("CategoryPost", b =>
                {
                    b.HasOne("Blog.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Data.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
