// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230108220303_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blog.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "My Business World"
                        },
                        new
                        {
                            Id = 3,
                            Name = "My Travels"
                        },
                        new
                        {
                            Id = 4,
                            Name = "My Kitchen"
                        });
                });

            modelBuilder.Entity("Blog.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7533),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7542),
                            Title = "Sample Text 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7568),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7568),
                            Title = "Sample Text 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7570),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7570),
                            Title = "Sample Text 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7571),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7572),
                            Title = "Sample Text 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7573),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7573),
                            Title = "Sample Text 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7575),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7575),
                            Title = "Sample Text 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7576),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7576),
                            Title = "Sample Text 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7578),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7578),
                            Title = "Sample Text 8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7579),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7580),
                            Title = "Sample Text 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7581),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7581),
                            Title = "Sample Text 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7583),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7583),
                            Title = "Sample Text 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7584),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7585),
                            Title = "Sample Text 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7586),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7586),
                            Title = "Sample Text 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7587),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7588),
                            Title = "Sample Text 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7589),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7589),
                            Title = "Sample Text 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7590),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7591),
                            Title = "Sample Text 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7592),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7592),
                            Title = "Sample Text 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7593),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7593),
                            Title = "Sample Text 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7594),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7595),
                            Title = "Sample Text 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7595),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7596),
                            Title = "Sample Text 20"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7597),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7597),
                            Title = "Sample Text 21"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7598),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7599),
                            Title = "Sample Text 22"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7600),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7600),
                            Title = "Sample Text 23"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7601),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7601),
                            Title = "Sample Text 24"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7602),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7602),
                            Title = "Sample Text 25"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7603),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7603),
                            Title = "Sample Text 26"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7604),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7605),
                            Title = "Sample Text 27"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7606),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7606),
                            Title = "Sample Text 28"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7607),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7608),
                            Title = "Sample Text 29"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7608),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7609),
                            Title = "Sample Text 30"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7610),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7610),
                            Title = "Sample Text 31"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7611),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7611),
                            Title = "Sample Text 32"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7612),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7612),
                            Title = "Sample Text 33"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7613),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7614),
                            Title = "Sample Text 34"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7615),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7615),
                            Title = "Sample Text 35"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7616),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7616),
                            Title = "Sample Text 36"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7617),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7618),
                            Title = "Sample Text 37"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7618),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7619),
                            Title = "Sample Text 38"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7620),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7620),
                            Title = "Sample Text 39"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7621),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7621),
                            Title = "Sample Text 40"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7622),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7622),
                            Title = "Sample Text 41"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7623),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7624),
                            Title = "Sample Text 42"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7625),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7625),
                            Title = "Sample Text 43"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7626),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7626),
                            Title = "Sample Text 44"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7651),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7651),
                            Title = "Sample Text 45"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7652),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7652),
                            Title = "Sample Text 46"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7653),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7654),
                            Title = "Sample Text 47"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7654),
                            DateOfUpdate = new DateTime(2023, 1, 9, 1, 3, 3, 38, DateTimeKind.Local).AddTicks(7655),
                            Title = "Sample Text 48"
                        });
                });

            modelBuilder.Entity("Blog.Data.Post", b =>
                {
                    b.HasOne("Blog.Data.Category", "Categories")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Blog.Data.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
