// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blog.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "My Business World"
                        },
                        new
                        {
                            Id = 3,
                            Name = "My Travels"
                        },
                        new
                        {
                            Id = 4,
                            Name = "My Kitchen"
                        });
                });

            modelBuilder.Entity("Blog.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7335),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7347),
                            Title = "Sample Text 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7368),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7368),
                            Title = "Sample Text 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7369),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7369),
                            Title = "Sample Text 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7370),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7371),
                            Title = "Sample Text 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7372),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7372),
                            Title = "Sample Text 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7373),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7373),
                            Title = "Sample Text 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7374),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7375),
                            Title = "Sample Text 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7376),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7376),
                            Title = "Sample Text 8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7377),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7377),
                            Title = "Sample Text 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7378),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7378),
                            Title = "Sample Text 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7379),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7380),
                            Title = "Sample Text 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7380),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7381),
                            Title = "Sample Text 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7382),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7382),
                            Title = "Sample Text 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7383),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7383),
                            Title = "Sample Text 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7384),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7384),
                            Title = "Sample Text 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7385),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7385),
                            Title = "Sample Text 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7386),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7386),
                            Title = "Sample Text 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7387),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7388),
                            Title = "Sample Text 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7388),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7389),
                            Title = "Sample Text 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7389),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7390),
                            Title = "Sample Text 20"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7410),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7410),
                            Title = "Sample Text 21"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7411),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7411),
                            Title = "Sample Text 22"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7412),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7413),
                            Title = "Sample Text 23"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7413),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7414),
                            Title = "Sample Text 24"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7415),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7415),
                            Title = "Sample Text 25"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7416),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7416),
                            Title = "Sample Text 26"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7417),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7417),
                            Title = "Sample Text 27"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7418),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7419),
                            Title = "Sample Text 28"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7419),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7420),
                            Title = "Sample Text 29"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7420),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7421),
                            Title = "Sample Text 30"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7421),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7422),
                            Title = "Sample Text 31"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7422),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7423),
                            Title = "Sample Text 32"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7424),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7424),
                            Title = "Sample Text 33"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7425),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7425),
                            Title = "Sample Text 34"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7426),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7426),
                            Title = "Sample Text 35"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7427),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7427),
                            Title = "Sample Text 36"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7428),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7428),
                            Title = "Sample Text 37"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7429),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7429),
                            Title = "Sample Text 38"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7430),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7430),
                            Title = "Sample Text 39"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7431),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7432),
                            Title = "Sample Text 40"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7432),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7433),
                            Title = "Sample Text 41"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7433),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7434),
                            Title = "Sample Text 42"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7434),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7435),
                            Title = "Sample Text 43"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7436),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7436),
                            Title = "Sample Text 44"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7437),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7437),
                            Title = "Sample Text 45"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7438),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7438),
                            Title = "Sample Text 46"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7439),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7439),
                            Title = "Sample Text 47"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Content = " \r\n                            <p>Tincidunt integer eu augue augue nunc elit dolor, luctus          placerat scelerisque euismod, iaculis eu lacus nunc mi elit,        vehicula ut laoreet ac, aliquam sit amet justo nunc                 tempor, metus vel.</p>\r\n                            <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi      odio eget   lorem nulla condimentum tempor mattis ut vitae          feugiat augue cras ut       metus a risus iaculis scelerisque       eu ac ante.</p>",
                            CreationDate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7440),
                            DateOfUpdate = new DateTime(2023, 1, 4, 23, 25, 27, 140, DateTimeKind.Local).AddTicks(7440),
                            Title = "Sample Text 48"
                        });
                });

            modelBuilder.Entity("CategoryPost", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "PostsId");

                    b.HasIndex("PostsId");

                    b.ToTable("CategoryPost");
                });

            modelBuilder.Entity("CategoryPost", b =>
                {
                    b.HasOne("Blog.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Data.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
